name: Deploy and Destroy Static Website

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: pulumi login
      
      - name: Configure AWS OIDC Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            role-to-assume: ${{ env.PULUMI_AWS_ROLE_ARN }}
            role-session-name: GitHubActionsSession
            aws-region: us-west-2
             
      - name: Install Pulumi Dependencies
        run: |
          pip install pulumi pulumi-aws

      - name: Deploy with Pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_REGION: us-west-2
        run: |
          pulumi stack select dev
          pulumi up --yes

  destroy:
    needs: deploy  # Ensures 'destroy' runs only after 'deploy' completes successfully
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: pulumi login
      
      - name: Configure AWS OIDC Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.PULUMI_AWS_ROLE_ARN }}
          role-session-name: GitHubActionsSession
          aws-region: ca-central-1

      - name: Install Pulumi Dependencies
        run: |
          pip install pulumi pulumi-aws

      - name: Destroy Pulumi Resources
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_REGION: ca-central-1
        run: |
          pulumi stack select dev
          pulumi destroy --yes
          pulumi stack rm dev --yes